baseurl: /monaco-go
name: monaco-go
title: monaco-go
description: Go lang support using Language Server Protocol over WebSocket for the Monaco editor
theme: jekyll-theme-cayman
exclude:
- Gemfile
- Gemfile.lock
- README.md
- scripts

permalink: none

# Dependencies
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:title
defaults:
  - scope:
      type: ""
      type: pages
    values:
      layout: default

include: ['_pages']
exclude: [bower_components, node_modules]
keep_files: [bower_components, node_modules]

